### ISSUE TITLE
Add process load to FluidLoop

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-description-schema#102]
Recommend adding ProcessLoad (Watt) and ProcessSchedule fields to FluidLoop, to allow capturing scenarios when loops serve process loads. E.g., chiller in a hospital may be serving MRIs, or boiler may serve a combination of space and SWH loads. Without that, we may end up with loops not having any loads, and will also not able to check whether baseline loops are modeled with no process loads on them.

**Comment by JasonGlazer** [comment]
@mkarpman Is this helping to verify a requirement in Appendix G or another ruleset?

**Comment by mkarpman** [comment]
For example, Table G3.1 #12 allows modeling process load improvements. These improvements may apply to misc. equipment power or to process loads on loops.

**Comment by JasonGlazer** [comment]
Added MiscellaneousEquipment.remaining_fraction_chilled_water_loop to address this

**Comment by mkarpman** [comment]
I like the idea but am not quite following what fields you are suggesting to add. Seems like this would require referencing CHW or HW loop as energy_type?

**Comment by JasonGlazer** [comment]
This has to do with heat rejection not energy input so for an MRI the energy_type would be electricity. So the heat to the zone for one of those machines is 40% (I am just guessing) and the rest of the heat would be rejected to the loop. So the sensible_fraction would by 0.4, the latent_fraction would be 0.0 and remaining_fraction_chilled_water_loop would take the remaining heat not rejected to the space. 

I see now that really should be to a condenser loop rather than chilled water loop.
