### ISSUE TITLE
Design Day Schedules

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-description-schema#150]
To assess the following rule, "For baseline cooling sizing runs in residential dwelling units, the infiltration, occupants, lighting, gas and electricity using equipment hourly schedule shall be the same as the most used hourly weekday schedule from the annual simulation."

 It seems that if we want to check it, we'd need to add desing_heating_multiplier_schedule and desing_cooling_multiplier_scheduleto each applicable object (Occupant, InteriorLighting, Infiltration, MiscellaneousEquipment) and then verify whether that schedule is equal to the typical annual schedule or 1 or 0. 

Jason will address...here is the RDS that was created so you can see the expected implementation in the schema. https://github.com/pnnl/ruleset-checking-tool/pull/876

**Comment by JasonGlazer** [comment]
@claperle I have been thinking about this and exposing an entire annual schedule when we really only need 24 hourly values seems like the wrong way to go. What if we modify the Schedule data group to include two new fields "cooling_design_day_sequence" and "heating_design_day_sequence" which each take a 24 hour sequence of values. This approach would also avoid adding new fields all over since the Schedule itself would contain this.

**Comment by claperle** [comment]
@JasonGlazer That makes sense to me and does seem much easier. Thanks!

**Comment by JasonGlazer** [comment]
@claperle I was hoping to get a decision from the Schema WG about the BDE Climate Data Model to replace the current Schedule data group but we did not get to it during the discussion today. Obviously fixing this issue would make sense to wait until that decision would be made but since the Schema WG meets so infrequently, I may just go ahead and implement this as a draft. What do you think?

**Comment by claperle** [comment]
@JasonGlazer Are there any cons to implementing as a draft? I am not sure what the BDE Climate Data Model is. Shall we discuss this on the call on Thursday?

**Comment by claperle** [comment]
@JasonGlazer Schedules have been voted on and accepted by the working group so recommend no changes since RDSs and RCT have been developed based on the voted on schedules object. Makes sense to implement design day approach in the schema then.

**Comment by claperle** [comment]
@JasonGlazer no worries, they should be added to the Schedule data group.
