### ISSUE TITLE
Data Elements `___sized_based_on_design_day`

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#236]
With the change to the wording of these data elements, I think it is especially necessary to state in the notes exactly what is expected in order for the boolean to be `True`. The current descriptions say "True if the component is sized by the simulation software for the design day" but the reason the wording was changed was that the sizing does not necessarily need to be done by the software -- it can be sized based on design day calculations done outside of the software. 

So then are there any additional requirements for this to be `True` if calculations are done externally and then entered as an input? If an RPD Generation Software GUI allowed a user to check a checkbox that the component is sized based on design day, what would the help text say for them to confidently know that their definition of "sized based on design day" aligns with our definition?

**Comment by JasonGlazer** [comment]
@JacksonJ-KC could you suggest text for this? I believe during the last Schema WG call we decided that it should be "is_calculated_size" with some notes. I would appreciate your input on this.

**Comment by JacksonJ-KC** [comment]
Something to the effect of "True if systems are sized according to ASHRAE/ACCA Standard 183 using temperatures corresponding to the `Weather.cooling_design_day_type` and `Weather.heating_design_day_type` for the site climate. ASHRAE climatic design conditions can be referenced at http://ashrae-meteo.info/v2.0/places.php"

**Comment by JasonGlazer** [comment]
@JacksonJ-KC, it has been a long time since the discussion at the last Schema WG call, so I don't remember the conclusion, but what you are suggesting seems overly specific. Most simulation programs would probably have to say False when autosizing is used instead of True, so I am not sure that change makes sense. 

The reference the current schema has:

- HeatingSystem.design_capacity "Design capacity may be determined by sizing performed by the software.  This value should be provided if sized by the simulation software as an output or explicitly provided as a simulation input."
- HeatingSystem.is_sized_based_on_design_day "True if the component is sized by the simulation software for the design day"
- CoolingSystem.design_total_cool_capacity "Designed total cooling capacity. Design capacity may be determined by sizing performed by the software. This value should be provided if sized by the simulation software as an output or explicitly provided as a simulation input."
- CoolingSystem.design_sensible_cool_capacity "Designed sensible cooling capacity. Design sensible capacity may be determined by sizing performed by the software. This value should be provided if sized by the simulation as an output or explicitly provided as a simulation input."
- CoolingSystem.is_sized_based_on_design_day "True if the component is sized by the simulation software for the design day"
- FanSystem.minimum_airflow "The minimum airflow may be determined by sizing performed by the softare. This value should be provided if sized by the simulation software as an output or explicitly provided as a simulation input."
- Fan.design_airflow "The design airlow may be determined by sizing performed by the software. This value should be provided if sized by the simulation software as an output or explicitly provided as a simulation input."
- Fan.is_airflow_sized_based_on_design_day "True if the airflow is sized by the simulation software for the design day"
- Terminal.minimum_outdoor_airflow "This value should be provided if fan airflow determined by sizing performed by the software or explicitly provided."
- Terminal.heating_capacity "Only includes the heating capacity of the terminal for hot water or electric coil. This value should be provided if determined by sizing performed by the software or explicitly provided."
- Terminal.cooling_capacity "Only includes the cooling capacity of the terminal for chilled water coil for radiant or fan coil.  This value should be provided if determined by sizing performed by the software or explicitly provided."
- FluidLoopDesignAndControl.is_sized_using_coincident_load "True if the loop is sized based on coincident load"
- Pump.design_flow "This value should be provided if determined by sizing performed by the software or explicitly provided."
- Pump.is_flow_sized_based_on_design_day "True if the design_flow is sized by the simulation software for the design day"

Unfortunately, my notes from the meeting say that I should use "is_calculated_size" and not very helpful: "add some extensive notes."

**Comment by JacksonJ-KC** [comment]
Ok if the criteria is not that strict and we are only trying to determined if the capacity is based on a manufactured system capacity vs. a calculated value then I am less concerned about this issue

**Comment by JasonGlazer** [comment]
@JacksonJ-KC should I close this issue?

**Comment by JacksonJ-KC** [comment]
If moving forward with the proposed change `is_calculated_size` closing makes sense to me

**Comment by JasonGlazer** [comment]
@JacksonJ-KC sorry, I read your "less concerned" as we don't need to make a change. Could you please remind me why I couldn't just update the notes to say something different on this one.

**Comment by JacksonJ-KC** [comment]
Updating the notes I think works too! 

`True if the component is sized by the simulation software for the design day` is currently problematic because theoretically the design calculations do not need to be done within the software - they could be manual calculations. This opens the door for any hardcoded capacity values to be manually marked as True for these various `is_sized_based_on_design_day` data elements and my thought was we need to have clear instructions for when this can be True. 

I think it would also be helpful for 229 to provide direction on what this boolean should be if a dependency of the calculated capacity is hardcoded. For example, maybe a system's supply fan is able to "autosize" however all of the zones served have their supply airflow hardsized so the system fan airflow is effectively the sum of hardcoded zone values. In this case it seems clear that the system fan `is_sized_based_on_design_day` should be `False`. What if only one of the zones has hardcoded airflow?

**Comment by JasonGlazer** [comment]
Isn't the "sized by the **simulation** software" sufficient?

**Comment by JacksonJ-KC** [comment]
The only reason I would say no is because I remember Tim had an issue with that wording so maybe we should get his input before addressing/closing this issue

**Comment by TimMcDowell** [comment]
Maybe the wording from 90.1 could be used: determined in accordance with generally accepted engineering standards.

**Comment by JacksonJ-KC** [comment]
I support this for describing when the boolean should be True.

I wonder if it might be confusing for cases where it should be False. For example, if it is manufactured equipment and the capacity is entered based on the size of the manufactured equipment - would it be confusing? Could someone think that the manufactured or nominal capacity is stated in accordance with generally accepted engineering standards? And the nominal equipment was selected based on design day sizing? Maybe a slight stretch but I think there is some room for misinterpretation.

My concerns would be resolved if the data element is changed to `is_calculated_size` AND the note is updated to say: `determined in accordance with generally accepted engineering standards.` 

I do still think this sort of scenario should be explicitly addressed in the note as well:
> I think it would also be helpful for 229 to provide direction on what this boolean should be if a dependency of the calculated capacity is hardcoded. For example, maybe a system's supply fan is able to "autosize" however all of the zones served have their supply airflow hardsized so the system fan airflow is effectively the sum of hardcoded zone values. In this case it seems clear that the system fan is_sized_based_on_design_day should be False. What if only one of the zones has hardcoded airflow?

**Comment by JasonGlazer** [comment]
Addressed in 0.1.1 schema update
