### ISSUE TITLE
Plenums, above ceiling volumes, etc. and how they are classified

### ISSUE THREAD

**Issue by JasonGlazer** [open229/ruleset-model-description-schema#258]
During the January 12, 2024 schema workgroup call, we discussed issues related to plenums (used as part of a supply air or return air path from or to an HVAC system) as well as modeling of above-ceiling spaces (often called plenums even if they are not part of an air path) and how they should be counted and classified. No decision was made, but several issues were identified:
- based on the current rules and data available the RCT was classifing plenum spaces indirectly conditioned spaces and then the baseline was assuming that they would be assigned to a system.
- could check the height of the plenum space as we do with crawlspaces
- perhaps we should add "is_plenum" to the schema for spaces or zones
- modelers often create spaces in models called plenums that are that may or may not be air paths but are essentially extensions to the space below it
- the definition in 90.1 for "plenum" and "enclosed space" overlap which implies that it should be able to be classified as cooled, heated, indirectly conditioned, or semi heated.
- we may also need "is_not_counted_as_floor_area" or "is_part_of_hvac_system" to completely define these volumes

**Comment by JasonGlazer** [comment]
@KarenWGard and @weilixu please feel free to add more details and options

**Comment by JasonGlazer** [comment]
Another opinion: "Based on the definition: if nothing special is done: indirectly conditioned space if transfer grills are placed in the ceiling or if supply registers are installed in the plenum: part of the conditioned space. So, I think it's somewhat design dependant." and "that is how a non-ducted return works, however, there are not supply diffusers in the plenum, they always supply directly to the conditioned space.  the Plenum is only for return air."

**Comment by KarenWGard** [comment]
taking another look at **Space** instead of **Zone**, **Space.floor_area** is defined as:

`The floor area of a space within the building, including basements, mezzanine and intermediate-floored tiers, and penthouses with a headroom height of 7.5 ft or greater. It is measured from the exterior faces of walls or from the center-line of walls separating buildings, but excluding covered walkways, open roofed-over areas, porches and similar spaces, pipe trenches, exterior terraces or steps, chimneys, roof overhangs, and similar features. This is the floor area that is modeled.`

All plenums that I've come across in the real world have a head height of much less than 7.5', so these spaces correctly translated to the schema should not have a floor_area.  I believe this is why we haven't seen issues in section 6 (lighting), as those calculations are done based on floor_area.  Would it be acceptable to do the HVAC evaluation only on zones with total floor_area > 0?

Adding `is_plenum?` to each space or zone would be a more explicit solution...

**Comment by JasonGlazer** [comment]
Based on the September 20, 2024, discussion, schema working group call, add plenum, crawlspace, or interstitial spaces to the list of SpaceFunctionOptions. Defining these terms is essential.

**Comment by JasonGlazer** [comment]
Addressed in schema update 0.1.0
