### ISSUE TITLE
Do we want r_value in Material?

### ISSUE THREAD

**Issue by JasonGlazer** [open229/ruleset-model-description-schema#292]

**Comment by JacksonJ-KC** [comment]
I think we do want `r_value` in Material. I am less sure about `r_values` in Construction but I am leaning towards them both being helpful for their own use-cases. 

I see Material r_value as being helpful because it can be an indicator for the total resistance of the air films since the Construction u_value would include the air films + material resistance and the material r_value would not include the air films. 

It would be more difficult to accomplish this with the Construction `r_values` because those require corresponding `insulation_locations`.

**Comment by JacksonJ-KC** [comment]
here is an example simplified construction and my interpretation of what the correct answer should look like:

> 
                                           "construction": {
                                                "id": "Interior Wall 05",
                                                "surface_construction_input_option": "SIMPLIFIED",
                                                "primary_layers": [
                                                    {
                                                        "id": "Interior Wall Resistance 06",
                                                        "r_value": 0.350459266
                                                    }
                                                ],
                                                "u_factor": 1.695003982
                                            },

if you were to calculate the overall r_value from the construction `u_factor` you would find that the difference between that and the material `r_value` is the air film resistance.

**Comment by JasonGlazer** [comment]
Thanks. Closing the issue.
