### ISSUE TITLE
`ComponentLocationOptions` Not Exclusive

### ISSUE THREAD

**Issue by JacksonJ-KC** [open229/ruleset-model-description-schema#294]
There is very likely chance of overlap between options but only 1 can be used.

Ex. within a conditioned zone, within a semi-conditioned zone, within an unconditioned crawlspace

**Comment by JacksonJ-KC** [comment]
# ComponentLocationOptions
|    Enumerator     |   Description   | Notes |
| ----------------- | --------------- | ----- |
| `IN_ZONE`         | In a zone       |       |
| `CONDITIONED`     | Conditioned     |       |
| `SEMICONDITIONED` | Semiconditioned |       |
| `OUTSIDE`         | Outside         |       |
| `GARAGE`          | Garage          |       |
| `ATTIC`           | Attic           |       |
| `CRAWL_SPACE`     | Crawl space     |       |
| `UNDERGROUND`     | Underground     |       |
| `UNCONDITIONED`   | Unconditioned   |       |
| `OTHER`           | Other           |       |

**Comment by JasonGlazer** [comment]
I see your point. Perhaps some notes would clarify the priority of the selection for the component locations:

IN_ZONE — The component is located in a zone modeled in the simulation e.g., heat transfer through the surfaces surrounding the zone may impact the space temperature. This should be used instead of the other enumeration options when the zone is being modeled in the simulation. 
CONDITIONED—The component is not in a zone modeled in the simulation, and its location has thermal properties similar to those of a conditioned location.
SEMICONDITIONED—The component is not in a zone modeled in the simulation, and its location has thermal properties similar to those of a semi-conditioned location. It is usually kept warm enough to prevent freezing and often only cooled by passive ventilators.
OUTSIDE — The component is not in a zone modeled in the simulation, and its location has thermal properties similar to the outdoors.
GARAGE—The component is not in a zone modeled in the simulation, and its location has thermal properties similar to those of a garage. It may or may not have passive ventilators and share an insulated wall with a conditioned zone.
ATTIC—The component is not in a zone modeled in the simulation, and its location has thermal properties similar to those of an attic. It may have passive ventilators or not, is often warmer during summer, especially on sunny days, and may share an insulated ceiling with a conditioned zone.
CRAWL_SPACE—The component is not in a zone modeled in the simulation, and its location has thermal properties similar to those of a crawl space beneath a building. It may or may not have passive ventilators and share an insulated floor with a conditioned zone.
UNDERGROUND —The component is not in a zone modeled in the simulation, and its location has thermal properties similar to those of an underground area.
UNCONDITIONED —The component is not in a zone modeled in the simulation, and its location has thermal properties similar to those of an unconditioned area other than one of the other enumerations in this list.
OTHER —The component is not in a zone modeled in the simulation, and its location has thermal properties similar to those of an area not otherwise described by a different enumeration.

**Comment by JasonGlazer** [comment]
Addressed in the 0.1.1 schema update.
