### ISSUE TITLE
The data type $ID that references data group IDs do not show up in JSON schema

### ISSUE THREAD

**Issue by JasonGlazer** [open229/ruleset-model-description-schema#41]

**Comment by charliepnnl** [comment]
While https://github.com/open229/ruleset-model-report-schema/blob/master/schema-source/ASHRAE229.schema.yaml has a defined Data Type "ID", it does not have a "$ID" data type.  I see two possible solutions:

1. Use "ID" instead of "$ID".
2. Define "$ID" as a Data Type.  Simply copy the definition of "ID" and change its description appropriately.

Either way, the JSON Schema Type will be `string`.  "ID" and "$ID" are purely used to aid a human reader.

**Comment by JasonGlazer** [comment]
@charliepnnl I added $ID to the list of data types but then the regex's were not happy. I think because $ has a special meaning. Using just ID clouds the issue of what is a name and what is a reference. Do you understand regex well enough to try this? Otherwise, I'm just going to call it ReferenceID instead of $ID and call it a day.

**Comment by charliepnnl** [comment]
@JasonGlazer   I will take a look and get back to you.

**Comment by charliepnnl** [comment]
@JasonGlazer   Ok.  I see a couple of options:

1. By inserting `\\$?` into the middle of line 507 of meta.schema.json:
```"(^(?!(Rating|PerformanceMap|GridVariables|LookupVariables))\\$?[A-Z]([A-Z]|[a-z]|[0-9])*$)": {```
I was able to get the desired behavior.
2. In truth, I find `ReferenceID` more descriptive than `$ID`.

Let me know if you want me to create a pull request for the first option.

**Comment by JasonGlazer** [comment]
@charliepnnl thanks for figuring this out. I will go back in my notes and ask who suggested using ID and $ID and see why they suggested that. I agree about ReferenceID
